/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class CleanersPanel extends javax.swing.JPanel {

    /**
     * Creates new form CleanersPanel
     */
    public CleanersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cleanersTable = new javax.swing.JTable();
        cleanerNameTxt = new javax.swing.JTextField();
        cleanerDeptCombo = new javax.swing.JComboBox<>();
        lblName = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblAddButton = new javax.swing.JLabel();
        addCleanerBtn = new javax.swing.JButton();
        lblClearButton = new javax.swing.JLabel();
        lblUpdateButton = new javax.swing.JLabel();
        updateCleanerBtn = new javax.swing.JButton();
        lblDeleteButton = new javax.swing.JLabel();
        deleteCleanerBtn = new javax.swing.JButton();
        clearCleanerBtn = new javax.swing.JButton();

        cleanersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cleanersTable.setName("cleanersTable"); // NOI18N
        jScrollPane1.setViewportView(cleanersTable);

        cleanerNameTxt.setName("cleanerNameTxt"); // NOI18N

        cleanerDeptCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cleanerDeptCombo.setName("cleanerDeptCombo"); // NOI18N
        cleanerDeptCombo.addActionListener(this::cleanerDeptComboActionPerformed);

        lblName.setText("Name:");
        lblName.setName("lblName"); // NOI18N

        lblDepartment.setText("Department:");
        lblDepartment.setName("lblDepartment"); // NOI18N

        lblAddButton.setText("Add Button");
        lblAddButton.setName("lblAddButton"); // NOI18N

        addCleanerBtn.setText("Add");
        addCleanerBtn.setName("addCleanerBtn"); // NOI18N

        lblClearButton.setText("Clear Button");
        lblClearButton.setName("lblClearButton"); // NOI18N

        lblUpdateButton.setText("Update Button");
        lblUpdateButton.setName("lblUpdateButton"); // NOI18N

        updateCleanerBtn.setText("Update");
        updateCleanerBtn.setName("updateCleanerBtn"); // NOI18N

        lblDeleteButton.setText("Delete Button");
        lblDeleteButton.setName("lblDeleteButton"); // NOI18N

        deleteCleanerBtn.setText("Delete");
        deleteCleanerBtn.setName("deleteCleanerBtn"); // NOI18N

        clearCleanerBtn.setText("CLEAR");
        clearCleanerBtn.setName("clearCleanerBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblDepartment)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addCleanerBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateCleanerBtn, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(lblAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblUpdateButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(clearCleanerBtn)
                                .addComponent(deleteCleanerBtn)
                                .addComponent(lblDeleteButton)
                                .addComponent(lblClearButton)))
                        .addComponent(cleanerNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cleanerDeptCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cleanerDeptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDeleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteCleanerBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblClearButton)
                                .addGap(10, 10, 10)
                                .addComponent(clearCleanerBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCleanerBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUpdateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateCleanerBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cleanerDeptComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanerDeptComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanerDeptComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCleanerBtn;
    private javax.swing.JComboBox<String> cleanerDeptCombo;
    private javax.swing.JTextField cleanerNameTxt;
    private javax.swing.JTable cleanersTable;
    private javax.swing.JButton clearCleanerBtn;
    private javax.swing.JButton deleteCleanerBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddButton;
    private javax.swing.JLabel lblClearButton;
    private javax.swing.JLabel lblDeleteButton;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUpdateButton;
    private javax.swing.JButton updateCleanerBtn;
    // End of variables declaration//GEN-END:variables
}
