/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTotalMaterialHeader = new javax.swing.JLabel();
        lblLowStockHeader = new javax.swing.JLabel();
        lblTotalCleanersHead = new javax.swing.JLabel();
        lblRecentIssuances = new javax.swing.JLabel();
        lblLowStockNum = new javax.swing.JLabel();
        lblTotalMatNum = new javax.swing.JLabel();
        lblTotalCleanersNum = new javax.swing.JLabel();
        lblRecentIssNum = new javax.swing.JLabel();
        btnNavManMaterial = new javax.swing.JButton();
        btnNavManSuppliers = new javax.swing.JButton();
        btnNavIssueStock = new javax.swing.JButton();
        btnNavManCleaners = new javax.swing.JButton();
        btnNavViewReport = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblTotalMaterialHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalMaterialHeader.setText("Total Materials: ");

        lblLowStockHeader.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLowStockHeader.setText("Low-Stock Items: ");

        lblTotalCleanersHead.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalCleanersHead.setText("Total Cleaners:");

        lblRecentIssuances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRecentIssuances.setText("Recent Issuances: ");

        lblLowStockNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLowStockNum.setText("0");

        lblTotalMatNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalMatNum.setText("0");

        lblTotalCleanersNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalCleanersNum.setText("0");

        lblRecentIssNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRecentIssNum.setText("0");

        btnNavManMaterial.setText("Manage Materials");
        btnNavManMaterial.addActionListener(this::btnNavManMaterialActionPerformed);

        btnNavManSuppliers.setText("Manage Suppliers");
        btnNavManSuppliers.addActionListener(this::btnNavManSuppliersActionPerformed);

        btnNavIssueStock.setText("Issue Stock");
        btnNavIssueStock.addActionListener(this::btnNavIssueStockActionPerformed);

        btnNavManCleaners.setText("Manage Cleaners");
        btnNavManCleaners.addActionListener(this::btnNavManCleanersActionPerformed);

        btnNavViewReport.setText("View Report");
        btnNavViewReport.addActionListener(this::btnNavViewReportActionPerformed);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("SMARTER CLEAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btnLogOut))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNavManSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNavManMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNavManCleaners)
                                    .addComponent(btnNavIssueStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNavViewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(289, 289, 289)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTotalCleanersNum)
                                        .addGap(241, 241, 241))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblLowStockNum)
                                        .addGap(242, 242, 242)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTotalMatNum)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblRecentIssNum)
                                        .addGap(55, 55, 55))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblLowStockHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTotalCleanersHead, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTotalMaterialHeader)
                                    .addComponent(lblRecentIssuances)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLowStockHeader)
                            .addComponent(lblTotalMaterialHeader))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLowStockNum)
                            .addComponent(lblTotalMatNum))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalCleanersHead)
                            .addComponent(lblRecentIssuances))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalCleanersNum)
                            .addComponent(lblRecentIssNum))
                        .addGap(287, 287, 287)
                        .addComponent(btnLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNavManCleaners)
                        .addGap(44, 44, 44)
                        .addComponent(btnNavManSuppliers)
                        .addGap(42, 42, 42)
                        .addComponent(btnNavManMaterial)
                        .addGap(36, 36, 36)
                        .addComponent(btnNavIssueStock)
                        .addGap(43, 43, 43)
                        .addComponent(btnNavViewReport)))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
 /*-----------------------------------------------------------------------------
    NAV BUTTONS
    
    Navigation Logic here
    ----------------------------------------------------------------------------
 */     
    
    
    private void btnNavManCleanersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavManCleanersActionPerformed
        
        
    }//GEN-LAST:event_btnNavManCleanersActionPerformed

    private void btnNavViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavViewReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnNavViewReportActionPerformed

    private void btnNavManSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavManSuppliersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavManSuppliersActionPerformed

    private void btnNavManMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavManMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavManMaterialActionPerformed

    private void btnNavIssueStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavIssueStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNavIssueStockActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNavIssueStock;
    private javax.swing.JButton btnNavManCleaners;
    private javax.swing.JButton btnNavManMaterial;
    private javax.swing.JButton btnNavManSuppliers;
    private javax.swing.JButton btnNavViewReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLowStockHeader;
    private javax.swing.JLabel lblLowStockNum;
    private javax.swing.JLabel lblRecentIssNum;
    private javax.swing.JLabel lblRecentIssuances;
    private javax.swing.JLabel lblTotalCleanersHead;
    private javax.swing.JLabel lblTotalCleanersNum;
    private javax.swing.JLabel lblTotalMatNum;
    private javax.swing.JLabel lblTotalMaterialHeader;
    // End of variables declaration//GEN-END:variables
}
