/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalMaterialHeaderlbl = new javax.swing.JLabel();
        LowStockHeaderlbl = new javax.swing.JLabel();
        TotalCleanersHeadlbl = new javax.swing.JLabel();
        RecentIssuanceslbl = new javax.swing.JLabel();
        LowStockNumlnl = new javax.swing.JLabel();
        TotalMatNumlbl = new javax.swing.JLabel();
        TotalCleanersNumlbl = new javax.swing.JLabel();
        RecentIssNumlbl = new javax.swing.JLabel();
        NavManMaterialbtn = new javax.swing.JButton();
        NavManSuppliersbtn = new javax.swing.JButton();
        NavIssueStockbtn = new javax.swing.JButton();
        NavManCleanersbtn = new javax.swing.JButton();
        NavViewReportbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();
        SmarterCleanlbl = new javax.swing.JLabel();

        TotalMaterialHeaderlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalMaterialHeaderlbl.setText("Total Materials: ");

        LowStockHeaderlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LowStockHeaderlbl.setText("Low-Stock Items: ");

        TotalCleanersHeadlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalCleanersHeadlbl.setText("Total Cleaners:");

        RecentIssuanceslbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RecentIssuanceslbl.setText("Recent Issuances: ");

        LowStockNumlnl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LowStockNumlnl.setText("0");

        TotalMatNumlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalMatNumlbl.setText("0");

        TotalCleanersNumlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TotalCleanersNumlbl.setText("0");

        RecentIssNumlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RecentIssNumlbl.setText("0");

        NavManMaterialbtn.setText("Manage Materials");
        NavManMaterialbtn.addActionListener(this::NavManMaterialbtnActionPerformed);

        NavManSuppliersbtn.setText("Manage Suppliers");
        NavManSuppliersbtn.addActionListener(this::NavManSuppliersbtnActionPerformed);

        NavIssueStockbtn.setText("Issue Stock");
        NavIssueStockbtn.addActionListener(this::NavIssueStockbtnActionPerformed);

        NavManCleanersbtn.setText("Manage Cleaners");
        NavManCleanersbtn.addActionListener(this::NavManCleanersbtnActionPerformed);

        NavViewReportbtn.setText("View Report");
        NavViewReportbtn.addActionListener(this::NavViewReportbtnActionPerformed);

        LogOutbtn.setText("Log Out");
        LogOutbtn.addActionListener(this::LogOutbtnActionPerformed);

        SmarterCleanlbl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        SmarterCleanlbl.setText("SMARTER CLEAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 118, Short.MAX_VALUE)
                .addComponent(NavManCleanersbtn)
                .addGap(26, 26, 26)
                .addComponent(NavManSuppliersbtn)
                .addGap(18, 18, 18)
                .addComponent(NavManMaterialbtn)
                .addGap(18, 18, 18)
                .addComponent(NavIssueStockbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NavViewReportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(LogOutbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(SmarterCleanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TotalCleanersNumlbl)
                                        .addGap(241, 241, 241))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LowStockNumlnl)
                                        .addGap(242, 242, 242)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TotalMatNumlbl)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RecentIssNumlbl)
                                        .addGap(55, 55, 55))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LowStockHeaderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalCleanersHeadlbl, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TotalMaterialHeaderlbl)
                                    .addComponent(RecentIssuanceslbl))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(SmarterCleanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(LogOutbtn)
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LowStockHeaderlbl)
                            .addComponent(TotalMaterialHeaderlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LowStockNumlnl)
                            .addComponent(TotalMatNumlbl))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalCleanersHeadlbl)
                            .addComponent(RecentIssuanceslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalCleanersNumlbl)
                            .addComponent(RecentIssNumlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NavManCleanersbtn)
                            .addComponent(NavManSuppliersbtn)
                            .addComponent(NavManMaterialbtn)
                            .addComponent(NavIssueStockbtn)
                            .addComponent(NavViewReportbtn))
                        .addGap(86, 86, 86))))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
 /*-----------------------------------------------------------------------------
    NAV BUTTONS
    
    Navigation Logic here
    ----------------------------------------------------------------------------
 */     
    
    
    private void NavManCleanersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavManCleanersbtnActionPerformed
        
        
    }//GEN-LAST:event_NavManCleanersbtnActionPerformed

    private void NavViewReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavViewReportbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NavViewReportbtnActionPerformed

    private void NavManSuppliersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavManSuppliersbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavManSuppliersbtnActionPerformed

    private void NavManMaterialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavManMaterialbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavManMaterialbtnActionPerformed

    private void NavIssueStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavIssueStockbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NavIssueStockbtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutbtnActionPerformed


    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JLabel LowStockHeaderlbl;
    private javax.swing.JLabel LowStockNumlnl;
    private javax.swing.JButton NavIssueStockbtn;
    private javax.swing.JButton NavManCleanersbtn;
    private javax.swing.JButton NavManMaterialbtn;
    private javax.swing.JButton NavManSuppliersbtn;
    private javax.swing.JButton NavViewReportbtn;
    private javax.swing.JLabel RecentIssNumlbl;
    private javax.swing.JLabel RecentIssuanceslbl;
    private javax.swing.JLabel SmarterCleanlbl;
    private javax.swing.JLabel TotalCleanersHeadlbl;
    private javax.swing.JLabel TotalCleanersNumlbl;
    private javax.swing.JLabel TotalMatNumlbl;
    private javax.swing.JLabel TotalMaterialHeaderlbl;
    // End of variables declaration//GEN-END:variables
}
