/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

import com.mycompany.prg381_project.BusinessLayer.CleanersService;
import com.mycompany.prg381_project.BusinessLayer.MaterialsService;
import com.mycompany.prg381_project.BusinessLayer.StockIssuanceService;

/**
 *
 * @author ASUS
 */
public class DashboardPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private final MaterialsService materialsService = new MaterialsService();
    private final CleanersService cleanersService = new CleanersService();
    private final StockIssuanceService stockIssuanceService = new StockIssuanceService();

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * Reloads the summary numbers from the database. Called by MainFrame
     * every time this panel is navigated to.
     */
    public void refreshStats() {
        int totalMaterials = materialsService.getAllMaterials().size();
        int lowStockCount = materialsService.getLowStockMaterials().size();
        int totalCleaners = cleanersService.getAllCleaners().size();
        int totalIssuances = stockIssuanceService.getIssuanceHistory().size();

        TotalMatNumlbl.setText(String.valueOf(totalMaterials));
        LowStockNumlnl.setText(String.valueOf(lowStockCount));
        TotalCleanersNumlbl.setText(String.valueOf(totalCleaners));
        RecentIssNumlbl.setText(String.valueOf(totalIssuances));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TotalMaterialHeaderlbl = new javax.swing.JLabel();
        LowStockHeaderlbl = new javax.swing.JLabel();
        TotalCleanersHeadlbl = new javax.swing.JLabel();
        RecentIssuanceslbl = new javax.swing.JLabel();
        LowStockNumlnl = new javax.swing.JLabel();
        TotalMatNumlbl = new javax.swing.JLabel();
        TotalCleanersNumlbl = new javax.swing.JLabel();
        RecentIssNumlbl = new javax.swing.JLabel();
        NavManMaterialbtn = new javax.swing.JButton();
        NavManSuppliersbtn = new javax.swing.JButton();
        NavIssueStockbtn = new javax.swing.JButton();
        NavManCleanersbtn = new javax.swing.JButton();
        NavViewReportbtn = new javax.swing.JButton();
        LogOutbtn = new javax.swing.JButton();
        SmarterCleanlbl = new javax.swing.JLabel();
        Menulbl = new javax.swing.JLabel();
        dashboardlbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(189, 224, 254));

        TotalMaterialHeaderlbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        TotalMaterialHeaderlbl.setText("Total Materials: ");

        LowStockHeaderlbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        LowStockHeaderlbl.setText("Low-Stock Items: ");

        TotalCleanersHeadlbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        TotalCleanersHeadlbl.setText("Total Cleaners:");

        RecentIssuanceslbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        RecentIssuanceslbl.setText("Total Issuances: ");

        LowStockNumlnl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        LowStockNumlnl.setText("0");

        TotalMatNumlbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        TotalMatNumlbl.setText("0");

        TotalCleanersNumlbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        TotalCleanersNumlbl.setText("0");

        RecentIssNumlbl.setFont(new java.awt.Font("Simplex_IV25", 0, 18)); // NOI18N
        RecentIssNumlbl.setText("0");

        NavManMaterialbtn.setText("Manage Materials");
        NavManMaterialbtn.addActionListener(this::NavManMaterialbtnActionPerformed);

        NavManSuppliersbtn.setText("Manage Suppliers");
        NavManSuppliersbtn.addActionListener(this::NavManSuppliersbtnActionPerformed);

        NavIssueStockbtn.setText("Issue Stock");
        NavIssueStockbtn.addActionListener(this::NavIssueStockbtnActionPerformed);

        NavManCleanersbtn.setText("Manage Cleaners");
        NavManCleanersbtn.addActionListener(this::NavManCleanersbtnActionPerformed);

        NavViewReportbtn.setText("View Report");
        NavViewReportbtn.addActionListener(this::NavViewReportbtnActionPerformed);

        LogOutbtn.setText("Log Out");
        LogOutbtn.addActionListener(this::LogOutbtnActionPerformed);

        SmarterCleanlbl.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        SmarterCleanlbl.setText("SMARTER CLEAN");

        Menulbl.setFont(new java.awt.Font("Simplex_IV50", 1, 18)); // NOI18N
        Menulbl.setText("Menu");

        dashboardlbl.setFont(new java.awt.Font("Simplex_IV25", 1, 18)); // NOI18N
        dashboardlbl.setText("Dashboard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(SmarterCleanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NavViewReportbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavManSuppliersbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavManCleanersbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavIssueStockbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavManMaterialbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Menulbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LowStockHeaderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TotalCleanersHeadlbl, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TotalMaterialHeaderlbl)
                                    .addComponent(RecentIssuanceslbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LogOutbtn)
                                        .addGap(14, 14, 14))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(LowStockNumlnl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(TotalCleanersNumlbl)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TotalMatNumlbl)
                                        .addGap(61, 61, 61))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RecentIssNumlbl)
                                        .addGap(55, 55, 55)))))
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dashboardlbl)
                        .addGap(299, 299, 299))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SmarterCleanlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Menulbl)
                            .addComponent(dashboardlbl))
                        .addGap(33, 33, 33)
                        .addComponent(NavManCleanersbtn)
                        .addGap(18, 18, 18)
                        .addComponent(NavManSuppliersbtn)
                        .addGap(18, 18, 18)
                        .addComponent(NavManMaterialbtn)
                        .addGap(18, 18, 18)
                        .addComponent(NavIssueStockbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LowStockHeaderlbl)
                            .addComponent(TotalMaterialHeaderlbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LowStockNumlnl)
                            .addComponent(TotalMatNumlbl))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalCleanersHeadlbl)
                            .addComponent(RecentIssuanceslbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalCleanersNumlbl)
                            .addComponent(RecentIssNumlbl))))
                .addGap(18, 18, 18)
                .addComponent(NavViewReportbtn)
                .addGap(53, 53, 53)
                .addComponent(LogOutbtn)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NavManCleanersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavManCleanersbtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.CLEANERS);
    }//GEN-LAST:event_NavManCleanersbtnActionPerformed

    private void NavViewReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavViewReportbtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.REPORTS);
    }//GEN-LAST:event_NavViewReportbtnActionPerformed

    private void NavManSuppliersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavManSuppliersbtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.SUPPLIERS);
    }//GEN-LAST:event_NavManSuppliersbtnActionPerformed

    private void NavManMaterialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavManMaterialbtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.MATERIALS);
    }//GEN-LAST:event_NavManMaterialbtnActionPerformed

    private void NavIssueStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NavIssueStockbtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.STOCK_ISSUANCE);
    }//GEN-LAST:event_NavIssueStockbtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        if (mainFrame != null) {
            mainFrame.clearCurrentUser();
            mainFrame.showPanel(MainFrame.LOGIN);
        }
    }//GEN-LAST:event_LogOutbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JLabel LowStockHeaderlbl;
    private javax.swing.JLabel LowStockNumlnl;
    private javax.swing.JLabel Menulbl;
    private javax.swing.JButton NavIssueStockbtn;
    private javax.swing.JButton NavManCleanersbtn;
    private javax.swing.JButton NavManMaterialbtn;
    private javax.swing.JButton NavManSuppliersbtn;
    private javax.swing.JButton NavViewReportbtn;
    private javax.swing.JLabel RecentIssNumlbl;
    private javax.swing.JLabel RecentIssuanceslbl;
    private javax.swing.JLabel SmarterCleanlbl;
    private javax.swing.JLabel TotalCleanersHeadlbl;
    private javax.swing.JLabel TotalCleanersNumlbl;
    private javax.swing.JLabel TotalMatNumlbl;
    private javax.swing.JLabel TotalMaterialHeaderlbl;
    private javax.swing.JLabel dashboardlbl;
    // End of variables declaration//GEN-END:variables
}
