/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class MaterialsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaterialsPanel
     */
    public MaterialsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        materialsTable = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        reorderLabel = new javax.swing.JLabel();
        qualityLabel = new javax.swing.JLabel();
        matNameTxt = new javax.swing.JTextField();
        matReorderTxt = new javax.swing.JTextField();
        matQtyTxt = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        matSearchTxt = new javax.swing.JTextField();
        matSearchBtn = new javax.swing.JButton();
        matAddBtn = new javax.swing.JButton();
        matUpdateBtn = new javax.swing.JButton();
        matDeleteBtn = new javax.swing.JButton();
        matClearBtn = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        matTable = new javax.swing.JTable();
        headingLabel = new javax.swing.JLabel();

        materialsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(materialsTable);

        setBackground(new java.awt.Color(189, 224, 254));
        setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        nameLabel.setText("Name:");

        reorderLabel.setText("Reorder:");

        qualityLabel.setText("Quality:");

        searchLabel.setText("Search:");

        matSearchBtn.setText("Search");
        matSearchBtn.addActionListener(this::matSearchBtnActionPerformed);

        matAddBtn.setText("Add");

        matUpdateBtn.setText("Update");

        matDeleteBtn.setText("Delete");

        matClearBtn.setText("Clear");

        matTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScroll.setViewportView(matTable);

        headingLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        headingLabel.setText("Materials Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tableScroll)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(matSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(reorderLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(matReorderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(matNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(qualityLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(matQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(matSearchBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(matAddBtn)
                                .addGap(18, 18, 18)
                                .addComponent(matUpdateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(matDeleteBtn)
                                .addGap(18, 18, 18)
                                .addComponent(matClearBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(headingLabel)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(headingLabel)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(qualityLabel)
                    .addComponent(matNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reorderLabel)
                    .addComponent(matReorderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(matSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matSearchBtn))
                .addGap(38, 38, 38)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matAddBtn)
                    .addComponent(matUpdateBtn)
                    .addComponent(matDeleteBtn)
                    .addComponent(matClearBtn))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void matSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matSearchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton matAddBtn;
    private javax.swing.JButton matClearBtn;
    private javax.swing.JButton matDeleteBtn;
    private javax.swing.JTextField matNameTxt;
    private javax.swing.JTextField matQtyTxt;
    private javax.swing.JTextField matReorderTxt;
    private javax.swing.JButton matSearchBtn;
    private javax.swing.JTextField matSearchTxt;
    private javax.swing.JTable matTable;
    private javax.swing.JButton matUpdateBtn;
    private javax.swing.JTable materialsTable;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel qualityLabel;
    private javax.swing.JLabel reorderLabel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
