/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

import com.mycompany.prg381_project.BusinessLayer.ReportsService;
import com.mycompany.prg381_project.model.materialsModel;
import com.mycompany.prg381_project.model.stockissuanceModel;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ReportsPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private final ReportsService reportsService = new ReportsService();

    private static final String INVENTORY = "Inventory Report";
    private static final String LOW_STOCK = "Low-Stock Report";
    private static final String ISSUANCE_HISTORY = "Issuance History";
    private static final String USAGE = "Material Usage Report";

    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel() {
        initComponents();
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        reportTypeLabel = new javax.swing.JLabel();
        repGenerateBtn = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        reportTypeCombo = new javax.swing.JComboBox<>();
        LogOutbtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(189, 224, 254));

        headingLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        headingLabel.setText("Reports");

        reportTypeLabel.setText("Report type:");

        repGenerateBtn.setText("Generate");
        repGenerateBtn.addActionListener(this::repGenerateBtnActionPerformed);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ));
        tableScroll.setViewportView(reportTable);

        reportTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { INVENTORY, LOW_STOCK, ISSUANCE_HISTORY, USAGE }));

        LogOutbtn.setText("Log Out");
        LogOutbtn.addActionListener(this::LogOutbtnActionPerformed);

        backBtn.setText("Back to Dashboard");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reportTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(reportTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(repGenerateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(headingLabel)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutbtn)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(45, 45, 45)
                .addComponent(headingLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportTypeLabel)
                    .addComponent(repGenerateBtn)
                    .addComponent(reportTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(LogOutbtn)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.DASHBOARD);
    }//GEN-LAST:event_backBtnActionPerformed

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        if (mainFrame != null) {
            mainFrame.clearCurrentUser();
            mainFrame.showPanel(MainFrame.LOGIN);
        }
    }//GEN-LAST:event_LogOutbtnActionPerformed

    private void repGenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGenerateBtnActionPerformed
        String reportType = (String) reportTypeCombo.getSelectedItem();
        if (reportType == null) return;

        switch (reportType) {
            case INVENTORY:
                showInventoryReport();
                break;
            case LOW_STOCK:
                showLowStockReport();
                break;
            case ISSUANCE_HISTORY:
                showIssuanceHistoryReport();
                break;
            case USAGE:
                showMaterialUsageReport();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_repGenerateBtnActionPerformed

    private void showInventoryReport() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Name", "Type", "Stock", "Reorder Level", "Date Added"}, 0);
        List<materialsModel> materials = reportsService.getInventoryReport();
        for (materialsModel m : materials) {
            model.addRow(new Object[]{
                m.getMaterialID(), m.getMName(), m.getType(), m.getStock(), m.getReorderLevel(), m.getDateAdded()
            });
        }
        reportTable.setModel(model);
    }

    private void showLowStockReport() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID", "Name", "Stock", "Reorder Level", "Shortfall"}, 0);
        for (materialsModel m : reportsService.getLowStockReport()) {
            int shortfall = Math.max(m.getReorderLevel() - m.getStock(), 0);
            model.addRow(new Object[]{ m.getMaterialID(), m.getMName(), m.getStock(), m.getReorderLevel(), shortfall });
        }
        reportTable.setModel(model);
    }

    private void showIssuanceHistoryReport() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Issue ID", "Material ID", "Cleaner ID", "Issued By (User ID)", "Quantity", "Date Issued", "Remaining Stock"}, 0);
        List<stockissuanceModel> records = reportsService.getIssuanceHistoryReport();
        for (stockissuanceModel r : records) {
            model.addRow(new Object[]{
                r.getIssuanceID(), r.getMaterialid(), r.getCleanerid(), r.getIssuedby(),
                r.getQuantity(), r.getDateIssued(), r.getRemainingstock()
            });
        }
        reportTable.setModel(model);
    }

    /**
     * Total quantity issued per material, computed here in the UI layer by
     * aggregating the issuance history and joining against the materials list
     * (no dedicated SQL aggregate query exists for this yet).
     */
    private void showMaterialUsageReport() {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"Material ID", "Material Name", "Total Quantity Issued"}, 0);
        for (ReportsService.MaterialUsageRow row : reportsService.getMaterialUsageReport()) {
            model.addRow(new Object[]{ row.materialId, row.materialName, row.totalIssued });
        }
        reportTable.setModel(model);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton repGenerateBtn;
    private javax.swing.JTable reportTable;
    private javax.swing.JComboBox<String> reportTypeCombo;
    private javax.swing.JLabel reportTypeLabel;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
