/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class ReportsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportsPanel
     */
    public ReportsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        reportTypeLabel = new javax.swing.JLabel();
        repGenerateBtn = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        reportTypeCombo = new javax.swing.JComboBox<>();
        LogOutbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(189, 224, 254));

        headingLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        headingLabel.setText("Reports");

        reportTypeLabel.setText("Report type:");

        repGenerateBtn.setText("Generate");
        repGenerateBtn.addActionListener(this::repGenerateBtnActionPerformed);

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScroll.setViewportView(reportTable);

        reportTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inventory Report", "Low-Stock Report", "Issuance History", "Material Usage Report" }));

        LogOutbtn.setText("Log Out");
        LogOutbtn.addActionListener(this::LogOutbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reportTypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(reportTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(repGenerateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(headingLabel)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutbtn)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(headingLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportTypeLabel)
                    .addComponent(repGenerateBtn)
                    .addComponent(reportTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(LogOutbtn)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutbtnActionPerformed
        // TODO add your handling code here:

        javax.swing.JFrame parentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        parentFrame.getContentPane().removeAll();

        parentFrame.getContentPane().add(new LoginPanel(), java.awt.BorderLayout.CENTER);

        parentFrame.revalidate();
        parentFrame.repaint();
    }//GEN-LAST:event_LogOutbtnActionPerformed

    private void repGenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repGenerateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repGenerateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutbtn;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton repGenerateBtn;
    private javax.swing.JTable reportTable;
    private javax.swing.JComboBox<String> reportTypeCombo;
    private javax.swing.JLabel reportTypeLabel;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
