/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class StockIssuancePanel extends javax.swing.JPanel {

    /**
     * Creates new form StockIssuancePanel
     */
    public StockIssuancePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockIssuancelbl = new javax.swing.JLabel();
        cmbCleaner = new javax.swing.JComboBox<>();
        selectStafflbl = new javax.swing.JLabel();
        selectMaterialslbl = new javax.swing.JLabel();
        cmbMaterials = new javax.swing.JComboBox<>();
        quantitylbl = new javax.swing.JLabel();
        issuanceLogScrlPnl = new javax.swing.JScrollPane();
        issuanceLogtbl = new javax.swing.JTable();
        spnQuantity = new javax.swing.JSpinner();
        issueStockbtn = new javax.swing.JButton();

        stockIssuancelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stockIssuancelbl.setText("Stock Issuance");

        cmbCleaner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCleaner.addActionListener(this::cmbCleanerActionPerformed);

        selectStafflbl.setText("Select staff/cleaner");

        selectMaterialslbl.setText("Select Material");

        cmbMaterials.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quantitylbl.setText("Quantity");

        issuanceLogtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Issue ID", "Cleaner Name", "Material", "Quantity"
            }
        ));
        issuanceLogScrlPnl.setViewportView(issuanceLogtbl);

        issueStockbtn.setText("Issue Stock");
        issueStockbtn.addActionListener(this::issueStockbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(stockIssuancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectStafflbl)
                            .addComponent(selectMaterialslbl)
                            .addComponent(quantitylbl))
                        .addGap(18, 18, 18)
                        .addComponent(cmbCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(issueStockbtn)
                                .addGap(76, 76, 76)))
                        .addComponent(issuanceLogScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(stockIssuancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectStafflbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectMaterialslbl)
                            .addComponent(cmbMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantitylbl)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(issueStockbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issuanceLogScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCleanerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCleanerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCleanerActionPerformed

    private void issueStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueStockbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueStockbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCleaner;
    private javax.swing.JComboBox<String> cmbMaterials;
    private javax.swing.JScrollPane issuanceLogScrlPnl;
    private javax.swing.JTable issuanceLogtbl;
    private javax.swing.JButton issueStockbtn;
    private javax.swing.JLabel quantitylbl;
    private javax.swing.JLabel selectMaterialslbl;
    private javax.swing.JLabel selectStafflbl;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JLabel stockIssuancelbl;
    // End of variables declaration//GEN-END:variables
}
