/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

import com.mycompany.prg381_project.BusinessLayer.StockIssuanceService;
import com.mycompany.prg381_project.BusinessLayer.exceptions.BusinessException;
import com.mycompany.prg381_project.model.cleanerModel;
import com.mycompany.prg381_project.model.materialsModel;
import com.mycompany.prg381_project.model.stockissuanceModel;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StockIssuancePanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    private final StockIssuanceService stockIssuanceService = new StockIssuanceService();

    /** Combo box entries carry the real ID while displaying a readable label. */
    private static class ComboItem {
        final int id;
        final String label;
        ComboItem(int id, String label) { this.id = id; this.label = label; }
        @Override public String toString() { return label; }
    }

    /**
     * Creates new form StockIssuancePanel
     */
    public StockIssuancePanel() {
        initComponents();
    }

    public void setMainFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockIssuancelbl = new javax.swing.JLabel();
        cmbCleaner = new javax.swing.JComboBox<>();
        selectStafflbl = new javax.swing.JLabel();
        selectMaterialslbl = new javax.swing.JLabel();
        cmbMaterials = new javax.swing.JComboBox<>();
        quantitylbl = new javax.swing.JLabel();
        issuanceLogScrlPnl = new javax.swing.JScrollPane();
        issuanceLogtbl = new javax.swing.JTable();
        spnQuantity = new javax.swing.JSpinner();
        issueStockbtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(189, 224, 254));

        stockIssuancelbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stockIssuancelbl.setText("Stock Issuance");

        selectStafflbl.setText("Select staff/cleaner");

        selectMaterialslbl.setText("Select Material");

        quantitylbl.setText("Quantity");

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100000, 1));

        issuanceLogtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Issue ID", "Cleaner Name", "Material", "Quantity", "Date Issued", "Remaining Stock"
            }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        issuanceLogScrlPnl.setViewportView(issuanceLogtbl);

        issueStockbtn.setText("Issue Stock");
        issueStockbtn.addActionListener(this::issueStockbtnActionPerformed);

        backBtn.setText("Back to Dashboard");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(stockIssuancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectStafflbl)
                            .addComponent(selectMaterialslbl)
                            .addComponent(quantitylbl))
                        .addGap(18, 18, 18)
                        .addComponent(cmbCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(issueStockbtn)
                                .addGap(76, 76, 76)))
                        .addComponent(issuanceLogScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(14, 14, 14)
                .addComponent(stockIssuancelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCleaner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectStafflbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectMaterialslbl)
                            .addComponent(cmbMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantitylbl)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(issueStockbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issuanceLogScrlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        if (mainFrame != null) mainFrame.showPanel(MainFrame.DASHBOARD);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * Reloads the Material/Cleaner dropdowns and the issuance log table.
     * Called at startup and by MainFrame every time this panel is navigated to,
     * so the dropdowns always reflect current stock and never go stale.
     */
    public void refreshData() {
        loadMaterialsCombo();
        loadCleanersCombo();
        loadIssuanceLog();
    }

    private void loadMaterialsCombo() {
        DefaultComboBoxModel<ComboItem> model = new DefaultComboBoxModel<>();
        for (materialsModel m : stockIssuanceService.getAllMaterials()) {
            model.addElement(new ComboItem(m.getMaterialID(),
                m.getMName() + " (in stock: " + m.getStock() + ")"));
        }
        cmbMaterials.setModel(model);
    }

    private void loadCleanersCombo() {
        DefaultComboBoxModel<ComboItem> model = new DefaultComboBoxModel<>();
        for (cleanerModel c : stockIssuanceService.getAllCleaners()) {
            model.addElement(new ComboItem(c.getID(), c.getName()));
        }
        cmbCleaner.setModel(model);
    }

    private void loadIssuanceLog() {
        DefaultTableModel model = (DefaultTableModel) issuanceLogtbl.getModel();
        model.setRowCount(0);

        List<stockissuanceModel> records = stockIssuanceService.getIssuanceHistory();
        for (stockissuanceModel r : records) {
            materialsModel mat = stockIssuanceService.getMaterialById(r.getMaterialid());
            cleanerModel cl = stockIssuanceService.getCleanerById(r.getCleanerid());
            model.addRow(new Object[]{
                r.getIssuanceID(),
                cl != null ? cl.getName() : ("#" + r.getCleanerid()),
                mat != null ? mat.getMName() : ("#" + r.getMaterialid()),
                r.getQuantity(),
                r.getDateIssued(),
                r.getRemainingstock()
            });
        }
    }

    private void issueStockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueStockbtnActionPerformed
        ComboItem selectedMaterial = (ComboItem) cmbMaterials.getSelectedItem();
        ComboItem selectedCleaner = (ComboItem) cmbCleaner.getSelectedItem();

        if (selectedMaterial == null || selectedCleaner == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select both a material and a cleaner. If either list is empty, add one first on its own screen.",
                "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int quantity = (Integer) spnQuantity.getValue();
        int issuedBy = (mainFrame != null) ? mainFrame.getCurrentUserId() : -1;

        try {
            stockIssuanceService.issueStock(selectedMaterial.id, selectedCleaner.id, issuedBy, quantity);
            javax.swing.JOptionPane.showMessageDialog(this, "Stock issued successfully.");
            spnQuantity.setValue(1);
            refreshData();
        } catch (BusinessException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            refreshData();
        }
    }//GEN-LAST:event_issueStockbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<ComboItem> cmbCleaner;
    private javax.swing.JComboBox<ComboItem> cmbMaterials;
    private javax.swing.JScrollPane issuanceLogScrlPnl;
    private javax.swing.JTable issuanceLogtbl;
    private javax.swing.JButton issueStockbtn;
    private javax.swing.JLabel quantitylbl;
    private javax.swing.JLabel selectMaterialslbl;
    private javax.swing.JLabel selectStafflbl;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JLabel stockIssuancelbl;
    // End of variables declaration//GEN-END:variables
}
