/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.prg381_project.ui;

/**
 *
 * @author ASUS
 */
public class SuppliersPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuppliersPanel
     */
    public SuppliersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addSupBtn = new javax.swing.JButton();
        lblClearButton = new javax.swing.JLabel();
        updateSupBtn = new javax.swing.JButton();
        deleteSupBtn = new javax.swing.JButton();
        clearSupBtn = new javax.swing.JButton();
        lblAddButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppliersTable = new javax.swing.JTable();
        lblUpdateButton = new javax.swing.JLabel();
        lblDeleteButton = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        supNameTxt = new javax.swing.JTextField();
        supContactTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(189, 224, 254));

        addSupBtn.setText("Add");
        addSupBtn.setName("addSupBtn"); // NOI18N

        lblClearButton.setText("Clear Button");
        lblClearButton.setName("lblClearButton"); // NOI18N

        updateSupBtn.setText("Update");
        updateSupBtn.setName("updateSupBtn"); // NOI18N

        deleteSupBtn.setText("Delete");
        deleteSupBtn.setName("deleteSupBtn"); // NOI18N

        clearSupBtn.setText("CLEAR");
        clearSupBtn.setName("clearSupBtn"); // NOI18N

        lblAddButton.setText("Add Button");
        lblAddButton.setName("lblAddButton"); // NOI18N

        suppliersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        suppliersTable.setName("suppliersTable"); // NOI18N
        jScrollPane1.setViewportView(suppliersTable);

        lblUpdateButton.setText("Update Button");
        lblUpdateButton.setName("lblUpdateButton"); // NOI18N

        lblDeleteButton.setText("Delete Button");
        lblDeleteButton.setName("lblDeleteButton"); // NOI18N

        lblName.setText("Name");
        lblName.setName("lblName"); // NOI18N

        lblContact.setText("Contact");
        lblContact.setToolTipText("");
        lblContact.setName("lblContact"); // NOI18N

        supNameTxt.setText("jTextField1");
        supNameTxt.setName("supNameTxt"); // NOI18N

        supContactTxt.setText("jTextField2");
        supContactTxt.setName("supContactTxt"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName)
                    .addComponent(clearSupBtn)
                    .addComponent(deleteSupBtn)
                    .addComponent(addSupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateSupBtn)
                    .addComponent(lblAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpdateButton)
                    .addComponent(lblDeleteButton)
                    .addComponent(lblClearButton)
                    .addComponent(lblContact)
                    .addComponent(supNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(supContactTxt))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblContact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supContactTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSupBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateSupBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteSupBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblClearButton)
                        .addGap(10, 10, 10)
                        .addComponent(clearSupBtn)))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSupBtn;
    private javax.swing.JButton clearSupBtn;
    private javax.swing.JButton deleteSupBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddButton;
    private javax.swing.JLabel lblClearButton;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDeleteButton;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUpdateButton;
    private javax.swing.JTextField supContactTxt;
    private javax.swing.JTextField supNameTxt;
    private javax.swing.JTable suppliersTable;
    private javax.swing.JButton updateSupBtn;
    // End of variables declaration//GEN-END:variables
}
